### ISSUE TITLE
subscribe page - show plans by default?

### ISSUE THREAD

**Issue by os72** [TryGhost/Lyra#114]
hello, thank you for ghost and this great theme

is there perhaps a plan to change the subscribe page and show the payment plans by default (instead of just the signup)?
that would be consistent with the subscribe pop-up flow (portal button flow)

look&feel would be similar to https://rediverge.com/membership/

**Comment by matthanley** [comment]
Hey @os72!

You can customise the theme to suit your requirements - the relevant docs for working with member signup in themes are [here](https://ghost.org/docs/members/checkout-buttons/).

**Comment by os72** [comment]
thanks @matthanley 
i'm new to ghost, couldn't figure out how the portal is implemented. could you point me to it?
that would help with customizing the subscribe page
thanks!

**Comment by matthanley** [comment]
Portal is an additional client-side script that's enabled through Ghost Admin. Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!

**Comment by os72** [comment]
yes i did and actually cross-referenced to the question here
unfortunately no response yet..
https://forum.ghost.org/t/subscribe-page-vs-portal-lyra-theme/18171
