### ISSUE TITLE
Mobile Friendly Version?

### ISSUE THREAD

**Issue by GMichaelRapp** [TryGhost/Lyra#12]
The Lyra theme doesn’t really feel very mobile friendly. The top menu gets cut off, which is a pain. I depend on mobile users and want to make their experience the best possible experience. Is there a way to make the menu show up as a sort of compressed (stacked) menu, where users only have to click on the three horizontal lines for more menu options?

**Comment by stoqe** [comment]
to clarify @GMichaelRapp, it's only the mobile menu you're questioning; not the rest of the theme? 

i'm a huge @TryGhost fan myself and i'm greatful for the free casper and lyra themes. however: this horizontal mobile menu hurts my heart and, imo, is a hopeless user experience that goes against ghost's "function over fancy" awesomeness. i think it says everything that the ghost website (ghost.org) uses the familiar, industry-standard, hamburger-style of mobile website, so i don't understand why the mobile menu on the 2 default ghost themes is the way it is — so bad.

i was literally [asking about it this on twitter today](https://twitter.com/STOQE/status/1191477084201185281?s=20)...

**Comment by GMichaelRapp** [comment]
Yeah, just the mobile elements. The theme itself is wonderful. I really like its simplicity, which is hard to come by in a lot of CMS.

**Comment by MikeJLink** [comment]
To the contrary, there's value in showing at least some of the navigation without having to click on the hamburger icon. For sites with a small amount of navigation, much better to just show the nav options.

**Comment by JohnONolan** [comment]
This is an intended interaction, not a bug :) it's open source, so you're very welcome to modify it for your needs either via  code injection, or your own copy of the theme

**Comment by maurobanze** [comment]
@JohnONolan can you please explain why? Currently, the subscribe button is not visible at all on mobile, due to my site name being long. Therefore, users need to scroll left on the menu bar in order to reveal the subscribe button. I can imagine people will have a hard time figuring this out, which is a big problem since subscribing functionality is vital and needs to be super accessible.

Thank you and sorry for commenting on a closed thread

**Comment by mikeywil** [comment]
This might help some who find this thread looking for solutions to this non-problem (;-) ... 
[https://github.com/jimmy-zhening-luo/mobile-friendly-ghost-casper](https://github.com/jimmy-zhening-luo/mobile-friendly-ghost-casper)
