### ISSUE TITLE
how to re-subscribe to newsletter?

### ISSUE THREAD

**Issue by os72** [TryGhost/Lyra#126]
Users are able to unsubscribe by clicking on the link provided in the newsletter email
Say that happens by accident, how can they re-subscribe?

Should this be an option on the "account" page?
(Eg, the portal button provides such option)

https://forum.ghost.org/t/user-re-subscribe-to-newsletter/19043

**Comment by minimaluminium** [comment]
Hey @os72. As of now, there's no way to detect if a user turned on/off newsletter subscription in theme handlebar templates. If this feature is mandatory for your situation, using Portal would make more sense.
