### ISSUE TITLE
No space between navigation and page content on mobile

### ISSUE THREAD

**Issue by ferdesmannen** [TryGhost/Lyra#30]
Affects both tag and author page.

https://github.com/TryGhost/Casper/issues/654

Only an issue on Lyra, not on Casper.

**Comment by TheodoreChu** [comment]
Yeah, there's definitely a problem with the header on Lyra that's not on Casper. I noticed that the problem is not as bad, though still present, when the tag page has an image on top.

**Comment by TheodoreChu** [comment]
It looks like this was improved with https://github.com/TryGhost/Lyra/commit/e94daab78777a439ab310d70efd7172d9cc4a321. Thank you @peterzimon

**Comment by kevinansfield** [comment]
Resolved in https://github.com/TryGhost/Lyra/commit/e94daab78777a439ab310d70efd7172d9cc4a321
