### ISSUE TITLE
Signup link in the footer doesn't navigate to /signup

### ISSUE THREAD

**Issue by 7hacker** [TryGhost/Lyra#33]
Signup link in the footer doesn't navigate to /signup
https://www.fastfunc.com/

**Comment by TheodoreChu** [comment]
Did you upload the `routes.yaml` as indicated on the [instructions](https://github.com/tryghost/lyra)?

**Comment by 7hacker** [comment]
Yes. I downloaded the routes.yaml from the admin dashboard and replicated it below for you

> routes:
>   /signup/: members/signup
>   /signin/: members/signin
>   /account/: members/account
> 
> collections:
>   /:
>     permalink: /{slug}/
>     template: index
> 
> taxonomies:
>   tag: /tag/{slug}/
>   author: /author/{slug}/

The issue might be in the HTML (see screenshot attached)
![Screen Shot 2020-02-11 at 1 45 07 PM](https://user-images.githubusercontent.com/1928815/74282300-bd3eab00-4cd4-11ea-8fd5-686e19ccc342.png)

**Comment by TheodoreChu** [comment]
OK, I see the problem. The [`default.hbs`](https://github.com/TryGhost/Lyra/blob/master/default.hbs) file needs to be updated. In line 34, it should be:
`<a href="{{@site.url}}/signup">Signup</a>`

**Comment by TheodoreChu** [comment]
I added a fix here: https://github.com/TryGhost/Lyra/pull/36/commits/1092c73c68793772cd5c8a549357d0d6f74f0fd4

**Comment by 7hacker** [comment]
Woot! 🎆 

I'm using the hosted service, so I imagine the next release should automatically update this for me and I wouldn't need to do anything on my end
