### ISSUE TITLE
User signup flow problematic when the publication is free

### ISSUE THREAD

**Issue by maurobanze** [TryGhost/Lyra#37]
I'm building a free publication (maurobanze.com) with newsletter functionality. Therefore, I'm using members functionality with Lyra theme. When a new member signs up, after clicking on the email confirmation link sent by email, they are directed to the "subscription plans" page, with the plans showing "0 usd/month". Clicking on the "Choose plan" button on either plan does nothing. The user still shows on the Members section within the admin, so they were successfully signed up. However, this is bad UX as the user is not sure that they have successfully subscribed to the publication (no success message). 

In my opinion the solution should either be to not show the "subscription plans" page at all if no money is being charged for the publication (instead, replace it with a success message). Alternatively, direct the user to that same page, but make the buttons work. Choosing a plan shouldn't require users to input payment information in this case, as the publication is free.

Why not use Casper then if the publication is free? I need the membership functionality as the site is a newsletter.

Thank you

**Comment by TheodoreChu** [comment]
If you want all of your content to be free but like the layout of Lyra, then the default Casper may be a good option. Is there a reason why you prefer Lyra to Casper? The purpose of Lyra is to have some posts that require payment

**Comment by maurobanze** [comment]
Hi Theodore, thank you for your reply. The reason why I'm using Lyra instead of Casper is that I would like to offer newsletter subscription functionality. I want people to be able to subscribe to my newsletter, and it would be easy if I could achieve that using only Ghost. I understand that Casper does not provide membership functionality, right? Ghost already provides membership functionality with no payment needed from the readers, evidenced by the ability to configure your site to accept free membership (see picture below). However, it seems like Lyra does not account for this use case.
<img width="956" alt="Screen Shot 2020-02-18 at 15 43 39" src="https://user-images.githubusercontent.com/6880879/74741444-72d5a500-5265-11ea-9b30-548d5611c502.png">

**Comment by kevinansfield** [comment]
@maurobanze Lyra is explicitly designed for a _paid_ membership site. The default Casper theme does have basic "free subscriber" members functionality included, as @TheodoreChu said maybe that's a better starting point for your use-case?

**Comment by maurobanze** [comment]
Hey @kevinansfield thank you for your reply. I was not aware that Casper offered membership functionality. I think it was not made clear on the docs. Thank you very much!
