### ISSUE TITLE
Image sizes on page.hbs and post.hbs are not the same with Casper

### ISSUE THREAD

**Issue by TheodoreChu** [TryGhost/Lyra#39]
On [Lyra/page.hbs](https://github.com/TryGhost/Lyra/blob/master/page.hbs), lines 36-37, we have:
```
                            (max-width: 1170px) 700px,
                            1400px"
```
This is different from [Lyra/post.hbs](https://github.com/TryGhost/Lyra/blob/master/post.hbs), lines 101-102:
```
                            (max-width: 1170px) 1170px,
                                2000px"
```
On Casper, they are the same. This is [Casper/page.hbs](https://github.com/TryGhost/Casper/blob/master/page.hbs), lines 36-37:
```
                            (max-width: 1170px) 1170px,
                            2000px"
```
This is [Casper/post.hbs](https://github.com/TryGhost/Casper/blob/master/post.hbs), lines 98-99:
```
                        (max-width: 1170px) 1170px,
                            2000px"
```
Should we update the lines on [Lyra/page.hbs](https://github.com/TryGhost/Lyra/blob/master/page.hbs)? Is there a reason for the image sizes on Lyra?

**Comment by peterzimon** [comment]
fixed with https://github.com/TryGhost/Lyra/commit/47828b3f937ed2d9a46779def81c97e5b1dd3814

**Comment by TheodoreChu** [comment]
Should the `700px` in line 36 also be changed to `1170px`?

**Comment by TheodoreChu** [comment]
Thanks for working on this @peterzimon. Should the `700px` in line 36 also be changed to `1170px`?

**Comment by peterzimon** [comment]
Thanks @TheodoreChu for the good catch I missed that one. Fixed that with https://github.com/TryGhost/Lyra/commit/d8922378ddda626e26a1a72858d65b734ea52b2a
