### ISSUE TITLE
Preview a post in a members enabled app shows subscription notice.

### ISSUE THREAD

**Issue by FarazPatankar** [TryGhost/Lyra#4]
I recently upgraded to Ghost 3.0 and moved to Lyra to have the option of allowing my users to sign up and noticed this issue while creating a new post today.

Steps to reproduce:
1. Enable members
2. Start writing a new post.
3. Try to access the preview.

I am guessing this isn't the expected behavior and was wondering what the team thought about it. I've also been experiencing a couple of other small issues and am not quite sure about whether I should create a separate ticket for those. Let me know.

**Comment by casperbh96** [comment]
Note that the default option for post access is public, and even when the post access is set to public, this issue still exists.

I made a post on it on the ghost forums:
[https://forum.ghost.org/t/post-preview-is-broken-in-lyra/9802](https://forum.ghost.org/t/post-preview-is-broken-in-lyra/9802)

For me, this issue means that I have to find a workaround to preview posts before I publish them. One workaround is writing the post, and copying the post to a local ghost install with a modified Lyra. 

Remove the if-else statement in `post.hbs` at line 88 and only keep the first the code inside the if and not the else. Or copy-paste this code instead:

```hbs
{{#if feature_image}}
<figure class="post-full-image">
    {{!-- This is a responsive image, it loads different sizes depending on device
    https://medium.freecodecamp.org/a-guide-to-responsive-images-with-ready-to-use-templates-c400bd65c433 --}}
    <img
        srcset="{{img_url feature_image size="s"}} 300w,
                {{img_url feature_image size="m"}} 600w,
                {{img_url feature_image size="l"}} 1000w,
                {{img_url feature_image size="xl"}} 2000w"
        sizes="(max-width: 800px) 400px,
            (max-width: 1170px) 1170px,
                2000px"
        src="{{img_url feature_image size="xl"}}"
        alt="{{title}}"
    />
</figure>
{{/if}}
<section class="post-full-content">
    <div class="post-content">
        {{content}}
    </div>
</section>
```

**Comment by JohnONolan** [comment]
Thanks for reporting! Sounds like this issue is in Ghost and not Lyra, so closing here :)
