### ISSUE TITLE
Gravatar not loading

### ISSUE THREAD

**Issue by pateskinasy** [TryGhost/Lyra#41]
Hi Ghost team,

Love the recent Gravatar addition.

It however does not render the gravatar, neither on my deployment, nor on `lyra.ghost.io`, see image for `/account`

And yes, I do have a gravatar for the email address I've used.

For testing purposes, one can test their email here: https://en.gravatar.com/site/check/

<img width="1059" alt="Screenshot 2020-02-27 at 18 25 13" src="https://user-images.githubusercontent.com/18645509/75474495-00647380-598f-11ea-9e9b-b9d4dff409b2.png">

**Comment by pateskinasy** [comment]
For others in future, do the obvious thing and ... upgrade ghost :)

**Comment by GiacomoSilli** [comment]
I have the same problem, maybe it's because lyra.ghost.io isn't updated on the latest version. It currently uses 3.7

**Comment by pateskinasy** [comment]
Yes, I've just updated and all is working well now 🙌🏼
