### ISSUE TITLE
Fatal Errors

### ISSUE THREAD

**Issue by KontenaIndonesia** [TryGhost/Lyra#45]
Hi there, 

I discover an error upload. This is the screenshot --> https://jmp.sh/fPTs4wc

I'm using Ghost-Azure https://github.com/novogeek/Ghost-Azure/blob/master/README.md

How to fix this problem?

**Comment by kevinansfield** [comment]
@KontenaIndonesia the `{{price}}` helper was added in Ghost 3.4.0. Please upgrade to latest Ghost to use the latest versions of this theme 🙂
