### ISSUE TITLE
I can't upload routes.yaml file

### ISSUE THREAD

**Issue by mk0r** [TryGhost/Lyra#48]
I uploaded the Lyra zip theme file but I am not able to upload the routes.yaml file

<img width="712" alt="Screen Shot 2020-03-24 at 4 35 32 PM" src="https://user-images.githubusercontent.com/2099901/77486780-da938880-6ded-11ea-9205-8b43d11c5e63.png">

**Comment by gargol** [comment]
Hey @mk0r :wave: What error are you seeing? Can you please provide a bit more information on the exact steps to reproduce the error? I have just uploaded routes.yaml that comes with Lyra and it worked just fine on the latest version  of Ghost :thinking:

**Comment by mk0r** [comment]
I was not getting any error just as shown the .yaml file was not selectable in the file browser. it worked when I switched from safari to Chrome
