### ISSUE TITLE
Clicking "Magic Link" from e-mail after 10 minutes sends you to success page

### ISSUE THREAD

**Issue by casperbh96** [TryGhost/Lyra#5]
Here are the steps to reproduce:

1. Submit an e-mail into the subscriber form.
2. Verify that you received the e-mail and wait 10 minutes
3. After 10 minutes, click the link.

"You have successfully subscribed to <site>"

The above message is displayed and the user thinks everything is great. But it's not, because the user passed the 10 minute mark and the e-mail did not go through. A separate issue should be that you only have those 10 minutes, and you can't turn it off.

**Comment by JohnONolan** [comment]
This is not a bug. It's simply a limitation of the beta, unrelated to Lyra - if you have beta feedback you're very welcome to post it over on the forum :)
