### ISSUE TITLE
/signup and /signin go to 404

### ISSUE THREAD

**Issue by scottsemple** [TryGhost/Lyra#67]
I just activated the most recent master on a Ghost Pro account.

Both /signin and /signup go to a 404 page.

**Comment by exist2019** [comment]
I am getting 404 error on subscribe and log in here https://powai.info/signup/

**Comment by TheodoreChu** [comment]
Looks like you figured it out. For anyone else, please follow the instructions: https://github.com/TryGhost/Lyra#instructions
