### ISSUE TITLE
Custom base URL issue.

### ISSUE THREAD

**Issue by FarazPatankar** [TryGhost/Lyra#7]
I created a post on the forum but haven't really found a resolution. The post can be seen [here](https://forum.ghost.org/t/custom-base-url-issue-with-lyra/9784).

The issue within the codebase is that we use `/signup` instead of `concat @site.url "/signup"` so it doesn't really work with subdirectories. I fixed that on my end but the same issue I believe exists with emails and I can't really change those?

This is what the CTA in the email links to - `https://tryindigo.com/blog/?token=TOKEN&action=signup` and it ends up redirecting the user to `https://tryindigo.com/signup` instead of `https://tryindigo.com/blog/signup`.

Is this something I am expected to fix/handle on my own end because I am not sure if that's possible. Any help/pointers would be really appreciated because no one can sign in to the blog until this is fixed.

Thank you!

**Comment by JohnONolan** [comment]
Hey Faraz - looks like this is a small bug :) we'll fix this, but in the mean time if you want to resolve it on your side, the offending code which does this redirect is a small snippet of jQuery default.hbs

**Comment by FarazPatankar** [comment]
Hey John,

Thanks for the quick response. I've fixed it for now by just showing the signup success instead of redirecting the user to the checkout page and it seems to work correctly.

I had another quick question though, in the places where we use stuff like:
```
{{#if @member}}
  <script>window.location = '/';</script>
{{/if}}
```
Is there a way to _properly_ redirect the user to the root URL for the blog? I've currently just hardcoded it to `/blog` because if I use `window.location`, I get the base URL for my app and not the subdirectory.

**Comment by JohnONolan** [comment]
How about
```
{{#if @member}}
  <script>window.location = '{{@site.url}}';</script>
{{/if}}
```

? That's probably what we'll update this to by default

**Comment by FarazPatankar** [comment]
Oh, I didn't realize we could use the variables inside the `script` tags. I tried `  <script>window.location = @site.url;</script>` and it broke.

I'll update my code to use this as well. Thanks again, John!

Also, loving 3.0 and the theme and would be happy to help out if there are any issues you need help with!

**Comment by JohnONolan** [comment]
This is fixed in master now and will go out in the next release :) thanks for reporting
