### ISSUE TITLE
Any Plans To Convert This Into A Gatsby Starter 

### ISSUE THREAD

**Issue by amaljithev** [TryGhost/Lyra#71]
Any Plans To Convert This Into A Gatsby Starter Like Casper ?

**Comment by pieronoviello** [comment]
I guess it will only be done when the Members section is no longer in beta, but officially released.

**Comment by minimaluminium** [comment]
Hey @amaljithev, there is no plan to convert Lyra into a Gatsby starter at the moment. I will pass it to the team.
