### ISSUE TITLE
Watch members directory

### ISSUE THREAD

**Issue by elijahmurray** [TryGhost/Lyra#75]
I tried to create a pull request but can't push to the repo.

Need to add the members directory to gulp

Here: https://github.com/TryGhost/Lyra/blob/master/gulpfile.js#L35

and here: https://github.com/TryGhost/Lyra/blob/master/gulpfile.js#L83

**Comment by minimaluminium** [comment]
Hey @elijahmurray, `/members` directory is now included in the watcher in https://github.com/TryGhost/Lyra/commit/9435a4c6ca175a4baf659eaf7331842b90fe3e3e.
