### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by kteare** [TryGhost/Lyra#77]
I attempted to add Search360 to this theme using the Caspar description of how to do that.

I do get a search page - but no search box.

And the search page gives no results.

Are there plans to add a search function?

**Comment by matthanley** [comment]
Hey 👋 We ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our documentation. If you can't find an answer then our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
