### ISSUE TITLE
Where i can change content sends in email

### ISSUE THREAD

**Issue by savsofts** [TryGhost/Lyra#97]
I didn't find theme file for signup and login email content..
Please help me to locate

**Comment by TheodoreChu** [comment]
I think this is managed by Ghost Core and not the theme: 

* Sign up: https://github.com/TryGhost/Ghost/blob/master/core/server/services/members/emails/signup.js
* Sign in: https://github.com/TryGhost/Ghost/blob/master/core/server/services/members/emails/signin.js
